"""updated table books

Revision ID: 840b0d969a06
Revises: cd4d2372890d
Create Date: 2020-11-25 08:56:49.100580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840b0d969a06'
down_revision = 'cd4d2372890d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('year_published', sa.Integer(), nullable=True))
    op.alter_column('books', 'author',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_books_author'), 'books', ['author'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.create_index(op.f('ix_books_year_published'), 'books', ['year_published'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_year_published'), table_name='books')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_author'), table_name='books')
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'author',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('books', 'year_published')
    # ### end Alembic commands ###
